import type { CSSProperties } from "react";
import Link from "next/link";
import { ArrowRight, GraduationCap } from "lucide-react";
import {
  Reveal,
  RevealGroup,
  RevealItem,
  Hover,
} from "@/components/motion/primitives";
import { getArticleBridge } from "@/lib/article-bridge";

/**
 * The bridge out of an article and into the guides.
 *
 * Measured problem: of the people who land on an article since instrumentation
 * became reliable on Aug 3, 85% never visit another page on the site. They
 * arrive from a search like "no robot code driver station", get the one answer
 * they needed, and leave. Article readers and lesson readers reach /signup at
 * almost exactly the same rate (8.1% vs 8.3%), so article traffic is not worse
 * traffic. There was simply nothing to click.
 *
 * The two CTAs that already exist on this page both ask for an account, which
 * is the wrong ask for someone who just got their answer and owes us nothing.
 * This block makes a content promise instead: three named lessons that continue
 * this exact subject, plus the department they live in. No account required to
 * read any of them, and saying so is the point.
 *
 * Server component on purpose. It renders from a generated static map, so it
 * costs no query, adds no client JS, and is in the HTML for crawlers. Nothing
 * here branches on viewport or reduced-motion, so there is no hydration risk.
 *
 * The map is generated by ~/learnfrc-verify/gen-bridge.js. Articles with no
 * genuine lesson match are absent from it and this renders nothing for them,
 * which is deliberate: a dead end beats a confident wrong turn.
 */
export function ArticleNextStep({ slug }: { slug: string }) {
  const bridge = getArticleBridge(slug);
  if (!bridge || bridge.lessons.length === 0) return null;

  const { deptName, deptCount, dept, lessons } = bridge;

  return (
    <section className="mx-auto max-w-6xl px-4 pt-16 sm:px-6 lg:px-8">
      <Reveal>
        <div
          className="ac-tile overflow-hidden p-6 sm:p-8"
          style={{ "--a": "#2560e6" } as CSSProperties}
        >
          <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
            <div className="flex min-w-0 items-start gap-3">
              <span className="ac-badge flex h-11 w-11 shrink-0 items-center justify-center">
                <GraduationCap aria-hidden className="h-5 w-5" />
              </span>
              <div className="min-w-0">
                <p className="ac-eyebrow">Keep going</p>
                <h2 className="mt-1.5 font-display text-xl font-bold leading-tight tracking-tight sm:text-2xl">
                  This article is one piece of {deptName}
                </h2>
                <p className="mt-2 max-w-2xl text-[15px] leading-relaxed text-foreground/70">
                  You came here for one answer. These lessons teach the same
                  subject properly, in the order a team actually learns it. All{" "}
                  {deptCount} are free and none of them need an account to read.
                </p>
              </div>
            </div>
            <Link
              href={`/guides/${dept}`}
              className="ac-btn shrink-0 self-start text-sm sm:self-center"
            >
              Browse all {deptCount}
              <ArrowRight aria-hidden className="h-4 w-4" />
            </Link>
          </div>

          <RevealGroup className="mt-6 grid gap-3 sm:grid-cols-3">
            {lessons.map((l) => (
              <RevealItem key={l.href}>
                <Hover className="h-full" lift={-4}>
                  <Link
                    href={l.href}
                    className="ac-card group flex h-full flex-col gap-2 rounded-2xl p-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
                  >
                    <h3 className="font-display text-[15px] font-semibold leading-snug tracking-tight transition-colors group-hover:text-primary">
                      {l.title}
                    </h3>
                    {l.summary ? (
                      <p className="line-clamp-3 text-sm leading-relaxed text-foreground/65">
                        {l.summary}
                      </p>
                    ) : null}
                    <span className="mt-auto inline-flex items-center gap-1 pt-1 text-sm font-medium text-primary">
                      Read the lesson
                      <ArrowRight
                        aria-hidden
                        className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5"
                      />
                    </span>
                  </Link>
                </Hover>
              </RevealItem>
            ))}
          </RevealGroup>
        </div>
      </Reveal>
    </section>
  );
}
