import Link from "next/link";
import { getArticleBridge } from "@/lib/article-bridge";

/**
 * The bridge out of an article and into the guides.
 *
 * Measured problem: of the people who land on an article since instrumentation
 * became reliable on Aug 3, 85% never visit another page on the site. They
 * arrive from a search like "no robot code driver station", get the one answer
 * they needed, and leave. Article readers and lesson readers reach /signup at
 * almost exactly the same rate (8.1% vs 8.3%), so article traffic is not worse
 * traffic. There was simply nothing to click.
 *
 * The other block on this page asks for an account, which is the wrong ask for
 * someone who just got their answer and owes us nothing. This one makes a
 * content promise instead: three named lessons that continue this exact
 * subject, plus the department they live in, none of which needs an account.
 *
 * WHY IT IS THE BLUE BAND. The binder has exactly one inverted surface, and it
 * is spent where the page changes subject. This is that moment: everything
 * above it is the article, everything below it is what to read next. Full
 * bleed, ruled top and bottom in ink, so it works like a page break.
 *
 * Server component on purpose. It renders from a generated static map, so it
 * costs no query, adds no client JS, and is in the HTML for crawlers.
 *
 * The map is generated by ~/learnfrc-verify/gen-bridge.js. Articles with no
 * genuine lesson match are absent from it and this renders nothing for them,
 * which is deliberate: a dead end beats a confident wrong turn.
 */
export function ArticleNextStep({ slug }: { slug: string }) {
  const bridge = getArticleBridge(slug);
  if (!bridge || bridge.lessons.length === 0) return null;

  const { deptName, deptCount, dept, lessons } = bridge;

  return (
    <section className="nb-slab mt-[clamp(2.4rem,5vw,3.6rem)] py-[clamp(2.2rem,4.5vw,3.4rem)]">
      <div className="nb-wrap">
        <div className="flex flex-wrap items-end justify-between gap-x-8 gap-y-4">
          <div className="min-w-0">
            <p className="nb-slug text-[rgba(245,246,242,0.8)]">
              dept / {dept}
            </p>
            <h2 className="mt-2 max-w-[20ch] text-[clamp(1.55rem,1.1rem+1.7vw,2.5rem)]">
              This article is one page of {deptName}.
            </h2>
            <p className="mt-3 max-w-[48ch] text-[0.98rem] text-[rgba(245,246,242,0.85)]">
              You came for one answer. These teach the same subject properly,
              in the order a team actually learns it. All {deptCount} are free,
              and none of them need an account to read.
            </p>
          </div>

          {/* Card stock on ballpoint, because the slab's own blue is what a
              `nb-btn` fills with: a blue button on a blue band is a hole. */}
          <Link
            href={`/guides/${dept}`}
            className="nb-btn shrink-0 border-[var(--card)] bg-[var(--card)] text-[var(--blue)]"
          >
            Open all {deptCount}
          </Link>
        </div>

        {/* Three ruled columns rather than three cards: on an inverted band a
            card would be a bright rectangle competing with the heading, and
            `nb-hair` already flips to card stock inside a slab. */}
        <ol className="mt-[clamp(1.5rem,3vw,2.2rem)] grid gap-x-[clamp(1.4rem,3vw,2.6rem)] gap-y-0 min-[860px]:grid-cols-3">
          {lessons.map((l, i) => (
            <li key={l.href} className="nb-hair">
              <Link href={l.href} className="group block py-[clamp(0.9rem,1.8vw,1.15rem)]">
                <span className="nb-slug block text-[rgba(245,246,242,0.8)]">
                  lesson {String(i + 1).padStart(2, "0")}
                </span>
                <span className="mt-1.5 block font-bold leading-[1.12] tracking-[-0.02em] group-hover:underline group-hover:decoration-2 group-hover:underline-offset-[5px]">
                  {l.title}
                </span>
                {l.summary ? (
                  <span className="mt-2 block text-[0.9rem] leading-snug text-[rgba(245,246,242,0.85)]">
                    {l.summary}
                  </span>
                ) : null}
              </Link>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}
